steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/nkr-codelabs/test-ipl:${SHORT_SHA}'
      - '-f'
      - 'Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/nkr-codelabs/test-ipl:${SHORT_SHA}'
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '-f'
      - 'src/main/resources/kubernetes/deployment.yaml'
      - '--project=nkr-codelabs'
      - '--location=us-central1'
      - '--cluster=nkr-autopilot-gke-clust'
    env:
      - 'IMAGE_TAG=${SHORT_SHA}'
    timeout: '1200s'
substitutions:
  _IMAGE_TAG: ${SHORT_SHA}

images:
  - 'gcr.io/nkr-codelabs/test-ipl:${SHORT_SHA}'
