steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/nkr-codelabs/gcp-project-docker-repo/test-ipl:0.0.1', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/nkr-codelabs/gcp-project-docker-repo/test-ipl:0.0.1' ]
images: ['us-central1-docker.pkg.dev/nkr-codelabs/gcp-project-docker-repo/test-ipl:0.0.1']
