steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/nkr-codelabs/test-ipl:${_TIMESTAMP}'
      - '-f'
      - 'Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/nkr-codelabs/test-ipl:${_TIMESTAMP}'
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '-f'
      - 'src/main/resources/kubernetes/deployment.yaml'
      - '--project=nkr-codelabs'
      - '--location=us-central1'
      - '--cluster=nkr-autopilot-gke-clust'      
images:
  - 'gcr.io/nkr-codelabs/test-ipl:latest'
