steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/nkr-codelabs/test-ipl:0.1'
      - '-f'
      - 'Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/nkr-codelabs/test-ipl:0.1'
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '-f'
      - 'src/main/resources/kubernetes/deployment.yaml'
images:
  - 'gcr.io/nkr-codelabs/test-ipl:0.1'
