steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/involuted-river-396410/test-ipl:${SHORT_SHA}'
      - '--tag=gcr.io/involuted-river-396410/test-ipl:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/involuted-river-396410/test-ipl:${SHORT_SHA}'
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '-f'
      - 'src/main/resources/kubernetes/deployment.yaml'
      - '--project=involuted-river-396410'
      - '--location=us-central1'
      - '--cluster=nkr-autopilot-cluster-1'
    env:
      - 'IMAGE_TAG=${SHORT_SHA}'
    timeout: '1200s'
images:
  - 'gcr.io/involuted-river-396410/test-ipl:${SHORT_SHA}'
