apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipl-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ipl-test
  template:
    metadata:
      labels:
        app: ipl-test
    spec:
      containers:
        - name: ipl-test
          image: gcr.io/nkr-codelabs/test-ipl:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata: 
  name: ipl-test-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: ipl-test

